spring.application.name=searchEngine
spring.mongodb.uri=mongodb://localhost:27017/ecommerce_search
spring.data.mongodb.auto-index-creation=true
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.auto-offset-reset=earliest
spring.elasticsearch.uris=http://localhost:9200